module AddressBook {

	struct AddressAccountDetails {
		string name;
		string address;
		string phoneNumber;
		string email;
		any communicationClientOps;
		any jokenpoClientOps;
	};

	interface Address {
		void insert(in any addressAccountDetailsIn, out long addressId);
		void get(in long addressId, out any addressAccountDetailsOut);
		void getList(out any addressBook);
	};

};


module Communication {

	interface ClientOps {
		void callBack(in any message);
	};

	interface HandlerMessage {
		void registerCB(in ClientOps c, in any message);
		void addUserToChat(in long chatId, in long userId);
		void sendMessage(in long chatId, in long userId, in any message);
	};

};

module Jokenpo {

	interface ClientOps {
		void callBack(in any message);
	};

	interface HandlerGame {
		void registerCB(in ClientOps c, in any option);
		void newGame(in long gameId, in long playerOne, in long playerTwo);
		void sendAction(in long gameId, in long playerId, in any option);
	};

};