package AddressBook;


/**
* AddressBook/_AddressImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 12:24:55 AM IST
*/

public abstract class _AddressImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements AddressBook.Address, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AddressImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerCB", new java.lang.Integer (0));
    _methods.put ("insert", new java.lang.Integer (1));
    _methods.put ("get", new java.lang.Integer (2));
    _methods.put ("getList", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AddressBook/Address/registerCB
       {
         AddressBook.AddressBookOps c = AddressBook.AddressBookOpsHelper.read (in);
         int userId = in.read_long ();
         this.registerCB (c, userId);
         out = $rh.createReply();
         break;
       }

       case 1:  // AddressBook/Address/insert
       {
         org.omg.CORBA.Any addressAccountDetailsIn = in.read_any ();
         org.omg.CORBA.AnyHolder addressAccountDetailsOut = new org.omg.CORBA.AnyHolder ();
         this.insert (addressAccountDetailsIn, addressAccountDetailsOut);
         out = $rh.createReply();
         out.write_any (addressAccountDetailsOut.value);
         break;
       }

       case 2:  // AddressBook/Address/get
       {
         int addressId = in.read_long ();
         org.omg.CORBA.AnyHolder addressAccountDetailsOut = new org.omg.CORBA.AnyHolder ();
         this.get (addressId, addressAccountDetailsOut);
         out = $rh.createReply();
         out.write_any (addressAccountDetailsOut.value);
         break;
       }

       case 3:  // AddressBook/Address/getList
       {
         org.omg.CORBA.AnyHolder addressBook = new org.omg.CORBA.AnyHolder ();
         this.getList (addressBook);
         out = $rh.createReply();
         out.write_any (addressBook.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddressBook/Address:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AddressImplBase
