package AddressBook;


/**
* AddressBook/_AddressBookOpsImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 12:24:55 AM IST
*/

public abstract class _AddressBookOpsImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements AddressBook.AddressBookOps, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _AddressBookOpsImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callBackAddUser", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AddressBook/AddressBookOps/callBackAddUser
       {
         int senderId = in.read_long ();
         this.callBackAddUser (senderId);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddressBook/AddressBookOps:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _AddressBookOpsImplBase
