package AddressBook;


/**
* AddressBook/AddressBookOpsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:07:03 PM IST
*/

public abstract class AddressBookOpsPOA extends org.omg.PortableServer.Servant
 implements AddressBook.AddressBookOpsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callBackSetInviteList", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AddressBook/AddressBookOps/callBackSetInviteList
       {
         String availableList = in.read_string ();
         this.callBackSetInviteList (availableList);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddressBook/AddressBookOps:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AddressBookOps _this() 
  {
    return AddressBookOpsHelper.narrow(
    super._this_object());
  }

  public AddressBookOps _this(org.omg.CORBA.ORB orb) 
  {
    return AddressBookOpsHelper.narrow(
    super._this_object(orb));
  }


} // class AddressBookOpsPOA
