package AddressBook;


/**
* AddressBook/AddressOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Monday, April 7, 2014 10:55:08 PM IST
*/

public interface AddressOperations 
{
  void insert (org.omg.CORBA.Any addressAccountDetailsIn, org.omg.CORBA.AnyHolder addressAccountDetailsOut);
  void get (int addressId, org.omg.CORBA.AnyHolder addressAccountDetailsOut);
  void getList (org.omg.CORBA.AnyHolder addressBook);
} // interface AddressOperations
