package AddressBook;


/**
* AddressBook/AddressAccountDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 12:24:57 AM IST
*/

public final class AddressAccountDetails implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public String address = null;
  public String phoneNumber = null;
  public String email = null;

  public AddressAccountDetails ()
  {
  } // ctor

  public AddressAccountDetails (int _id, String _name, String _address, String _phoneNumber, String _email)
  {
    id = _id;
    name = _name;
    address = _address;
    phoneNumber = _phoneNumber;
    email = _email;
  } // ctor

} // class AddressAccountDetails
