package AddressBook;


/**
* AddressBook/AddressHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 7:11:56 PM IST
*/

abstract public class AddressHelper
{
  private static String  _id = "IDL:AddressBook/Address:1.0";

  public static void insert (org.omg.CORBA.Any a, AddressBook.Address that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AddressBook.Address extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AddressBook.AddressHelper.id (), "Address");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AddressBook.Address read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AddressStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AddressBook.Address value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AddressBook.Address narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AddressBook.Address)
      return (AddressBook.Address)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AddressBook._AddressStub stub = new AddressBook._AddressStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AddressBook.Address unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AddressBook.Address)
      return (AddressBook.Address)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AddressBook._AddressStub stub = new AddressBook._AddressStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
