package AddressBook;


/**
* AddressBook/AddressBookOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 12:24:57 AM IST
*/

public interface AddressBookOpsOperations 
{
  void callBackAddUser (int senderId);
} // interface AddressBookOpsOperations
