package AddressBook;


/**
* AddressBook/AddressBookOpsPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:07:03 PM IST
*/

public class AddressBookOpsPOATie extends AddressBookOpsPOA
{

  // Constructors

  public AddressBookOpsPOATie ( AddressBook.AddressBookOpsOperations delegate ) {
      this._impl = delegate;
  }
  public AddressBookOpsPOATie ( AddressBook.AddressBookOpsOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public AddressBook.AddressBookOpsOperations _delegate() {
      return this._impl;
  }
  public void _delegate (AddressBook.AddressBookOpsOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void callBackSetInviteList (String availableList)
  {
    _impl.callBackSetInviteList(availableList);
  } // callBackSetInviteList

  private AddressBook.AddressBookOpsOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AddressBookOpsPOATie
