package AddressBook;

/**
* AddressBook/AddressHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Sunday, April 6, 2014 2:49:11 AM IST
*/

public final class AddressHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBook.Address value = null;

  public AddressHolder ()
  {
  }

  public AddressHolder (AddressBook.Address initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBook.AddressHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBook.AddressHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBook.AddressHelper.type ();
  }

}
