package AddressBook;


/**
* AddressBook/Address_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 12:24:55 AM IST
*/

public class Address_Tie extends _AddressImplBase
{

  // Constructors
  public Address_Tie ()
  {
  }

  public Address_Tie (AddressBook.AddressOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (AddressBook.AddressBookOps c, int userId)
  {
    _impl.registerCB(c, userId);
  } // registerCB

  public void insert (org.omg.CORBA.Any addressAccountDetailsIn, org.omg.CORBA.AnyHolder addressAccountDetailsOut)
  {
    _impl.insert(addressAccountDetailsIn, addressAccountDetailsOut);
  } // insert

  public void get (int addressId, org.omg.CORBA.AnyHolder addressAccountDetailsOut)
  {
    _impl.get(addressId, addressAccountDetailsOut);
  } // get

  public void getList (org.omg.CORBA.AnyHolder addressBook)
  {
    _impl.getList(addressBook);
  } // getList

  private AddressBook.AddressOperations _impl;

} // class Address_Tie
