package AddressBook;


/**
* AddressBook/AddressBookOps_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:06:57 PM IST
*/

public class AddressBookOps_Tie extends _AddressBookOpsImplBase
{

  // Constructors
  public AddressBookOps_Tie ()
  {
  }

  public AddressBookOps_Tie (AddressBook.AddressBookOpsOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBackSetInviteList (String availableList)
  {
    _impl.callBackSetInviteList(availableList);
  } // callBackSetInviteList

  private AddressBook.AddressBookOpsOperations _impl;

} // class AddressBookOps_Tie
