package AddressBook;


/**
* AddressBook/AddressBookOps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:07:03 PM IST
*/

public interface AddressBookOps extends AddressBookOpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AddressBookOps
