package AddressBook;


/**
* AddressBook/AddressBookOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:07:03 PM IST
*/

public interface AddressBookOpsOperations 
{
  void callBackSetInviteList (String availableList);
} // interface AddressBookOpsOperations
