package Jokenpo;


/**
* Jokenpo/_HandlerGameStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 8:41:09 PM IST
*/

public class _HandlerGameStub extends org.omg.CORBA.portable.ObjectImpl implements Jokenpo.HandlerGame
{

  public void registerCB (Jokenpo.ClientOps c, org.omg.CORBA.Any option)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerCB", true);
                Jokenpo.ClientOpsHelper.write ($out, c);
                $out.write_any (option);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerCB (c, option        );
            } finally {
                _releaseReply ($in);
            }
  } // registerCB

  public void newGame (int gameId, int playerOne, int playerTwo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("newGame", true);
                $out.write_long (gameId);
                $out.write_long (playerOne);
                $out.write_long (playerTwo);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                newGame (gameId, playerOne, playerTwo        );
            } finally {
                _releaseReply ($in);
            }
  } // newGame

  public void sendAction (int gameId, int playerId, org.omg.CORBA.Any option)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendAction", true);
                $out.write_long (gameId);
                $out.write_long (playerId);
                $out.write_any (option);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                sendAction (gameId, playerId, option        );
            } finally {
                _releaseReply ($in);
            }
  } // sendAction

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Jokenpo/HandlerGame:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _HandlerGameStub
