package Jokenpo;


/**
* Jokenpo/ClientOps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 7:11:56 PM IST
*/

public interface ClientOps extends ClientOpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientOps
