package Jokenpo;


/**
* Jokenpo/ClientOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Sunday, April 6, 2014 2:49:11 AM IST
*/

public interface ClientOpsOperations 
{
  void callBack (org.omg.CORBA.Any message);
} // interface ClientOpsOperations
