package Jokenpo;


/**
* Jokenpo/ClientOpsPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 8:41:09 PM IST
*/

public class ClientOpsPOATie extends ClientOpsPOA
{

  // Constructors

  public ClientOpsPOATie ( Jokenpo.ClientOpsOperations delegate ) {
      this._impl = delegate;
  }
  public ClientOpsPOATie ( Jokenpo.ClientOpsOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Jokenpo.ClientOpsOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Jokenpo.ClientOpsOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void callBack (org.omg.CORBA.Any message)
  {
    _impl.callBack(message);
  } // callBack

  private Jokenpo.ClientOpsOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ClientOpsPOATie
