package Jokenpo;


/**
* Jokenpo/HandlerGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Monday, April 7, 2014 10:55:08 PM IST
*/

public interface HandlerGame extends HandlerGameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HandlerGame
