package Jokenpo;


/**
* Jokenpo/HandlerGameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 12:30:00 AM IST
*/

public interface HandlerGameOperations 
{
  void registerCB (Jokenpo.ClientOps c, org.omg.CORBA.Any option);
} // interface HandlerGameOperations
