package Jokenpo;


/**
* Jokenpo/HandlerGame_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:06:57 PM IST
*/

public class HandlerGame_Tie extends _HandlerGameImplBase
{

  // Constructors
  public HandlerGame_Tie ()
  {
  }

  public HandlerGame_Tie (Jokenpo.HandlerGameOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Jokenpo.JokenpoOps c, int userId)
  {
    _impl.registerCB(c, userId);
  } // registerCB

  public int createGame (int user1, int user2)
  {
    return _impl.createGame(user1, user2);
  } // createGame

  public void sendAction (int gameId, int playerId, org.omg.CORBA.Any option)
  {
    _impl.sendAction(gameId, playerId, option);
  } // sendAction

  private Jokenpo.HandlerGameOperations _impl;

} // class HandlerGame_Tie
