package Jokenpo;


/**
* Jokenpo/HandlerGame_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 8:41:04 PM IST
*/

public class HandlerGame_Tie extends _HandlerGameImplBase
{

  // Constructors
  public HandlerGame_Tie ()
  {
  }

  public HandlerGame_Tie (Jokenpo.HandlerGameOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Jokenpo.ClientOps c, org.omg.CORBA.Any option)
  {
    _impl.registerCB(c, option);
  } // registerCB

  public void newGame (int gameId, int playerOne, int playerTwo)
  {
    _impl.newGame(gameId, playerOne, playerTwo);
  } // newGame

  public void sendAction (int gameId, int playerId, org.omg.CORBA.Any option)
  {
    _impl.sendAction(gameId, playerId, option);
  } // sendAction

  private Jokenpo.HandlerGameOperations _impl;

} // class HandlerGame_Tie
