package Jokenpo;


/**
* Jokenpo/HandlerGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Sunday, April 6, 2014 5:26:33 PM IST
*/

public interface HandlerGame extends HandlerGameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HandlerGame
