package Jokenpo;


/**
* Jokenpo/HandlerGamePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 2:17:22 AM IST
*/

public class HandlerGamePOATie extends HandlerGamePOA
{

  // Constructors

  public HandlerGamePOATie ( Jokenpo.HandlerGameOperations delegate ) {
      this._impl = delegate;
  }
  public HandlerGamePOATie ( Jokenpo.HandlerGameOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Jokenpo.HandlerGameOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Jokenpo.HandlerGameOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registerCB (Jokenpo.JokenpoOps c, int userId)
  {
    _impl.registerCB(c, userId);
  } // registerCB

  public int createGame (int user1, int user2)
  {
    return _impl.createGame(user1, user2);
  } // createGame

  public void sendAction (int gameId, int playerId, org.omg.CORBA.Any option)
  {
    _impl.sendAction(gameId, playerId, option);
  } // sendAction

  private Jokenpo.HandlerGameOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HandlerGamePOATie
