package Jokenpo;


/**
* Jokenpo/HandlerGameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 2:17:22 AM IST
*/

public interface HandlerGameOperations 
{
  void registerCB (Jokenpo.JokenpoOps c, int userId);
  int createGame (int user1, int user2);
  void sendAction (int gameId, int playerId, org.omg.CORBA.Any option);
} // interface HandlerGameOperations
