package Jokenpo;

/**
* Jokenpo/JokenpoOpsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:07:03 PM IST
*/

public final class JokenpoOpsHolder implements org.omg.CORBA.portable.Streamable
{
  public Jokenpo.JokenpoOps value = null;

  public JokenpoOpsHolder ()
  {
  }

  public JokenpoOpsHolder (Jokenpo.JokenpoOps initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Jokenpo.JokenpoOpsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Jokenpo.JokenpoOpsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Jokenpo.JokenpoOpsHelper.type ();
  }

}
