package Jokenpo;


/**
* Jokenpo/JokenpoOps_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 12:24:55 AM IST
*/

public class JokenpoOps_Tie extends _JokenpoOpsImplBase
{

  // Constructors
  public JokenpoOps_Tie ()
  {
  }

  public JokenpoOps_Tie (Jokenpo.JokenpoOpsOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBackCreateGame (int gameId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackCreateGame(gameId, senderId, message);
  } // callBackCreateGame

  public void callBackShowdResult (int gameId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackShowdResult(gameId, senderId, message);
  } // callBackShowdResult

  private Jokenpo.JokenpoOpsOperations _impl;

} // class JokenpoOps_Tie
