package Jokenpo;


/**
* Jokenpo/JokenpoOps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 2:17:22 AM IST
*/

public interface JokenpoOps extends JokenpoOpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface JokenpoOps
