package Communication;


/**
* Communication/_HandlerMessageImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 8:41:04 PM IST
*/

public abstract class _HandlerMessageImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Communication.HandlerMessage, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _HandlerMessageImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerCB", new java.lang.Integer (0));
    _methods.put ("addUserToChat", new java.lang.Integer (1));
    _methods.put ("sendMessage", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Communication/HandlerMessage/registerCB
       {
         Communication.ClientOps c = Communication.ClientOpsHelper.read (in);
         int userId = in.read_long ();
         this.registerCB (c, userId);
         out = $rh.createReply();
         break;
       }

       case 1:  // Communication/HandlerMessage/addUserToChat
       {
         int chatId = in.read_long ();
         int userId = in.read_long ();
         this.addUserToChat (chatId, userId);
         out = $rh.createReply();
         break;
       }

       case 2:  // Communication/HandlerMessage/sendMessage
       {
         int userId = in.read_long ();
         org.omg.CORBA.Any message = in.read_any ();
         this.sendMessage (userId, message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Communication/HandlerMessage:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _HandlerMessageImplBase
