package Communication;


/**
* Communication/ClientOps_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Monday, April 7, 2014 10:55:06 PM IST
*/

public class ClientOps_Tie extends _ClientOpsImplBase
{

  // Constructors
  public ClientOps_Tie ()
  {
  }

  public ClientOps_Tie (Communication.ClientOpsOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBackCreateChat (int chatId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackCreateChat(chatId, senderId, message);
  } // callBackCreateChat

  public void callBackShowdMessage (int chatId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackShowdMessage(chatId, senderId, message);
  } // callBackShowdMessage

  private Communication.ClientOpsOperations _impl;

} // class ClientOps_Tie
