package Communication;


/**
* Communication/ClientOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Sunday, April 6, 2014 5:26:33 PM IST
*/

public interface ClientOpsOperations 
{
  void callBack (org.omg.CORBA.Any message);
} // interface ClientOpsOperations
