package Communication;


/**
* Communication/ClientOpsPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Monday, April 7, 2014 10:55:08 PM IST
*/

public class ClientOpsPOATie extends ClientOpsPOA
{

  // Constructors

  public ClientOpsPOATie ( Communication.ClientOpsOperations delegate ) {
      this._impl = delegate;
  }
  public ClientOpsPOATie ( Communication.ClientOpsOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public Communication.ClientOpsOperations _delegate() {
      return this._impl;
  }
  public void _delegate (Communication.ClientOpsOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void callBackCreateChat (int chatId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackCreateChat(chatId, senderId, message);
  } // callBackCreateChat

  public void callBackShowdMessage (int chatId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackShowdMessage(chatId, senderId, message);
  } // callBackShowdMessage

  private Communication.ClientOpsOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ClientOpsPOATie
