package Communication;


/**
* Communication/ClientOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 8:41:09 PM IST
*/

public interface ClientOpsOperations 
{
  void callBack (org.omg.CORBA.Any message);
} // interface ClientOpsOperations
