package Communication;


/**
* Communication/ClientOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Monday, April 7, 2014 10:55:08 PM IST
*/

public interface ClientOpsOperations 
{
  void callBackCreateChat (int chatId, int senderId, org.omg.CORBA.Any message);
  void callBackShowdMessage (int chatId, int senderId, org.omg.CORBA.Any message);
} // interface ClientOpsOperations
