package Communication;


/**
* Communication/CommunicationOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 4:07:03 PM IST
*/

public interface CommunicationOpsOperations 
{
  void callBackCreateChat (int chatId, int senderId, org.omg.CORBA.Any message);
  void callBackShowdMessage (int chatId, int senderId, org.omg.CORBA.Any message);
} // interface CommunicationOpsOperations
