package Communication;


/**
* Communication/CommunicationOps_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Tuesday, April 8, 2014 2:17:12 AM IST
*/

public class CommunicationOps_Tie extends _CommunicationOpsImplBase
{

  // Constructors
  public CommunicationOps_Tie ()
  {
  }

  public CommunicationOps_Tie (Communication.CommunicationOpsOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void callBackCreateChat (int chatId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackCreateChat(chatId, senderId, message);
  } // callBackCreateChat

  public void callBackShowdMessage (int chatId, int senderId, org.omg.CORBA.Any message)
  {
    _impl.callBackShowdMessage(chatId, senderId, message);
  } // callBackShowdMessage

  private Communication.CommunicationOpsOperations _impl;

} // class CommunicationOps_Tie
