package Communication;


/**
* Communication/HandlerMessage_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 7:11:55 PM IST
*/

public class HandlerMessage_Tie extends _HandlerMessageImplBase
{

  // Constructors
  public HandlerMessage_Tie ()
  {
  }

  public HandlerMessage_Tie (Communication.HandlerMessageOperations impl)
  {
    super ();
    _impl = impl;
  }

  public void registerCB (Communication.ClientOps c, org.omg.CORBA.Any message)
  {
    _impl.registerCB(c, message);
  } // registerCB

  public void addUserToChat (int chatId, int userId)
  {
    _impl.addUserToChat(chatId, userId);
  } // addUserToChat

  public void sendMessage (int chatId, int userId, org.omg.CORBA.Any message)
  {
    _impl.sendMessage(chatId, userId, message);
  } // sendMessage

  private Communication.HandlerMessageOperations _impl;

} // class HandlerMessage_Tie
