package Communication;


/**
* Communication/HandlerMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 8:41:09 PM IST
*/

public interface HandlerMessage extends HandlerMessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HandlerMessage
