package Communication;


/**
* Communication/HandlerMessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Sunday, April 6, 2014 2:49:11 AM IST
*/

public interface HandlerMessageOperations 
{
  void registerCB (Communication.ClientOps c, int userId);
  void addUserToChat (int chatId, int userId);
  void sendMessage (int userId, org.omg.CORBA.Any message);
} // interface HandlerMessageOperations
