package Communication;


/**
* Communication/HandlerMessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idlfile.idl
* Saturday, April 5, 2014 7:11:56 PM IST
*/

public interface HandlerMessageOperations 
{
  void registerCB (Communication.ClientOps c, org.omg.CORBA.Any message);
  void addUserToChat (int chatId, int userId);
  void sendMessage (int chatId, int userId, org.omg.CORBA.Any message);
} // interface HandlerMessageOperations
